### PR TITLE
fix: Visual glitch in alarm and clock lists

### LINKED ISSUE #264: Deleting an alarm changes which alarms are active
### Steps to reproduce

1. Create three alarms, e.g. 10:00, 11:00, 12:00.
2. Enable only the second alarm (11:00).
3. Delete the first alarm (10:00).

### Expected behavior

The alarm at 11:00 remains enabled, the alarm at 12:00 remains disabled.

### Actual behavior

The alarm at 12:00 is enabled instead, and the alarm at 11:00 is disabled.

### Clock You version

6.4

### Android version

13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #283: Wrong time displayed when adding new cities to world clock
### Steps to reproduce

1. Add two cities to the world clock, e.g. Almaty and Aqtau, that are _in different time zones_.
2. Add another city that is alphabetically before them.
3. Observe how the list shows _the same time_ for the first two cities until you switch to another tab and return back.

### Expected behavior

Correct time for all cities.

### Actual behavior

Wrong time for some of the cities.

### Clock You version

7.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by SuhasDissa**
fix #283
fix #264

### CODE REVIEW

File: app/src/main/java/com/bnyro/clock/ui/screens/AlarmScreen.kt [hunk 1]
```diff
@@ -112,7 +112,7 @@ fun AlarmScreen(
 
             }
 
-            items(alarms) {
+            items(items = alarms, key = { it.id }) {
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/clock/ui/screens/AlarmScreen.kt:115]: Very neat, I didn't know this feature/argument exists. That's probably very useful at other places of some You Apps too.

**Review by Bnyro — APPROVED** [review]

File: app/src/main/java/com/bnyro/clock/ui/screens/AlarmScreen.kt (hunk 1 above)
Comment (SuhasDissa) [reply app/src/main/java/com/bnyro/clock/ui/screens/AlarmScreen.kt:115]: I didn't know that until today. I discovered this while trying to fix a totally different problem.
